name: black

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Check the Black formatting
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        with:
          python_version: "3.8"

      - run: "python -m pip install black"
        name: Install black

      - name: Run Black
        run:  "python -m black --check . -l 99"
